/**
 * Website status classification.
 *
 * A single HTTP status code is not enough to decide whether a company has a real
 * website: parked domains return 200, Cloudflare challenges return 403, and plenty of
 * live sites redirect across hosts. This module takes everything we observed during the
 * probe and produces a status plus the evidence that justifies it.
 *
 * Critically, a site that blocks crawlers is NEVER reported as offline — being unable to
 * read a site is a limit of our measurement, not a fact about the business.
 */

import type { ConfidenceLevel, WebsiteStatus } from './types';
import { normalizeDomain } from './domain';

export type ProbeErrorCode = 'dns' | 'ssl' | 'timeout' | 'connection' | null;

export interface StatusProbe {
  submittedDomain: string | null;
  finalUrl: string | null;
  httpStatus: number | null;
  redirectChain: string[];
  errorCode: ProbeErrorCode;
  errorMessage?: string | null;
  html: string | null;
  textContent: string | null;
  title: string | null;
  headers?: Record<string, string>;
}

export interface StatusClassification {
  status: WebsiteStatus;
  reason: string;
  evidence: string[];
  confidence: ConfidenceLevel;
}

/**
 * Placeholder wording, split by how much weight one match deserves.
 *
 * STRONG phrases are ones a working business site never puts on its homepage — a registrar
 * template, a default server page, a sales pitch for the domain itself. Seeing one is
 * enough on its own.
 *
 * WEAK phrases are ones real sites use all the time. "Coming soon" is the clearest case:
 * it sits on a product badge in half the shops we look at, so matching it anywhere would
 * declare a trading store "under construction" and stop its analysis. Weak phrases only
 * count on a page that is *also* nearly empty, which is what a placeholder actually is.
 */
const PARKED_STRONG = [
  'this domain is parked',
  'domain parking',
  'parked free',
  'parkingcrew',
  'sedoparking',
  'this webpage was generated by the domain owner',
  'future home of something quite cool',
  'welcome to nginx',
  'apache2 ubuntu default page',
];

const PARKED_WEAK = ['default web site page', 'it works!'];

const FOR_SALE_STRONG = [
  'buy this domain',
  'this domain is for sale',
  'domain is for sale',
  'hugedomains',
  'afternic',
  'الدومين للبيع',
];

/** "dan.com" is a substring of jordan.com and sudan.com — it needs the empty-page gate. */
const FOR_SALE_WEAK = ['domain for sale', 'make an offer', 'dan.com'];

const CONSTRUCTION_STRONG = [
  'under construction',
  'site is being built',
  'website is under development',
  'تحت الإنشاء',
  'الموقع قيد الإنشاء',
];

const CONSTRUCTION_WEAK = ['coming soon', 'launching soon', 'be right back', 'قريباً', 'قريبا'];

/**
 * Wording that only ever appears *on* a challenge page. A real site does not greet you
 * with "Just a moment…", so finding one of these is conclusive on its own.
 */
const BOT_CHALLENGE_PHRASES = [
  'just a moment',
  'checking your browser',
  'enable javascript and cookies to continue',
  'attention required! | cloudflare',
  'ddos protection by',
  'please verify you are a human',
  'request unsuccessful. incapsula',
];

/**
 * Words that appear on plenty of perfectly healthy pages and mean nothing by themselves.
 *
 * "captcha" is the cautionary one: every Shopify store ships reCAPTCHA with its contact
 * form, so the word sits in the markup of a site that loaded perfectly. Matching it
 * anywhere in the HTML declared eleven working shops "bot protected" and stopped their
 * analysis dead — a false negative dressed up as caution, which is worse than no check at
 * all because it looks principled.
 *
 * These now count only on a page that is *also* empty, which is what a challenge actually
 * is: a few lines of text, no navigation, nothing to read.
 */
const BOT_WEAK_MARKERS = ['captcha', 'access denied', 'cf-chl', 'perimeterx'];

/** A challenge page carries almost nothing. A real page that mentions a captcha is full. */
const CHALLENGE_MAX_TEXT = 1_200;
const CHALLENGE_MAX_LINKS = 5;

/** Placeholder pages are thin too, though parking pages do carry a list of ad links. */
const PLACEHOLDER_MAX_TEXT = 2_000;
const PLACEHOLDER_MAX_LINKS = 15;

const BOT_PROTECTION_HEADERS = ['cf-mitigated', 'x-datadome', 'x-iinfo', 'x-sucuri-id'];

function contains(haystack: string, needles: string[]): string | null {
  for (const n of needles) {
    if (haystack.includes(n)) return n;
  }
  return null;
}

function crossedHost(chain: string[], finalUrl: string | null): boolean {
  const first = chain[0];
  if (!first || !finalUrl) return false;
  const a = normalizeDomain(first);
  const b = normalizeDomain(finalUrl);
  return a.ok && b.ok && a.domain !== b.domain;
}

/** Density of real page content, used to separate a thin placeholder from a real site. */
export function contentSignals(probe: StatusProbe): {
  textLength: number;
  linkCount: number;
  hasNav: boolean;
} {
  const html = probe.html ?? '';
  const text = (probe.textContent ?? '').replace(/\s+/g, ' ').trim();
  const linkCount = (html.match(/<a\s[^>]*href=/gi) ?? []).length;
  const hasNav = /<nav[\s>]|role=["']navigation["']/i.test(html);
  return { textLength: text.length, linkCount, hasNav };
}

export function classifyWebsiteStatus(probe: StatusProbe): StatusClassification {
  const evidence: string[] = [];

  if (!probe.submittedDomain || probe.submittedDomain.trim() === '') {
    return {
      status: 'no_website',
      reason: 'No website was supplied for this company in the import.',
      evidence: ['website column empty in source row'],
      confidence: 'high',
    };
  }

  const normalized = normalizeDomain(probe.submittedDomain);
  if (!normalized.ok) {
    return {
      status: 'invalid_domain',
      reason: `Submitted website could not be parsed as a domain (${normalized.reason}).`,
      evidence: [`submitted value: ${probe.submittedDomain}`, `rejection: ${normalized.reason}`],
      confidence: 'high',
    };
  }

  if (probe.redirectChain.length > 0) {
    evidence.push(`redirect chain: ${probe.redirectChain.join(' -> ')}`);
  }
  if (probe.httpStatus != null) evidence.push(`http status: ${probe.httpStatus}`);
  if (probe.finalUrl) evidence.push(`final url: ${probe.finalUrl}`);

  // --- Transport-level failures -------------------------------------------------
  if (probe.errorCode === 'dns') {
    return {
      status: 'dns_failure',
      reason: 'The domain did not resolve via DNS.',
      evidence: [...evidence, probe.errorMessage ?? 'DNS lookup failed'],
      confidence: 'high',
    };
  }
  if (probe.errorCode === 'ssl') {
    return {
      status: 'ssl_failure',
      reason: 'The site could not be loaded over HTTPS because of a TLS/certificate error.',
      evidence: [...evidence, probe.errorMessage ?? 'TLS handshake failed'],
      confidence: 'high',
    };
  }
  if (probe.errorCode === 'timeout') {
    return {
      status: 'timeout',
      reason: 'The site did not respond within the request timeout.',
      evidence: [...evidence, probe.errorMessage ?? 'request timed out'],
      confidence: 'medium',
    };
  }
  if (probe.errorCode === 'connection') {
    return {
      status: 'unknown_needs_review',
      reason: 'The connection failed for a reason we could not attribute; manual review required.',
      evidence: [...evidence, probe.errorMessage ?? 'connection error'],
      confidence: 'low',
    };
  }

  // Challenge wording is looked for in what the page *says*, not in its scripts: a
  // reCAPTCHA loader in the markup is not a challenge, it is a contact form.
  const visible = `${probe.title ?? ''} ${probe.textContent ?? ''}`.toLowerCase();
  const markup = `${visible} ${probe.html ?? ''}`.toLowerCase();
  const headerKeys = Object.keys(probe.headers ?? {}).map((k) => k.toLowerCase());

  const botHeader = BOT_PROTECTION_HEADERS.find((h) => headerKeys.includes(h));
  const challengePhrase = contains(visible, BOT_CHALLENGE_PHRASES);

  // A weak marker only counts on a page with nothing else on it.
  const density = contentSignals(probe);
  const looksEmpty = density.textLength < CHALLENGE_MAX_TEXT && density.linkCount <= CHALLENGE_MAX_LINKS;
  const weakMarker = looksEmpty ? contains(markup, BOT_WEAK_MARKERS) : null;

  /** Strong phrase anywhere on the page, or a weak one on a page with nothing else on it. */
  const thinEnoughForPlaceholder =
    density.textLength < PLACEHOLDER_MAX_TEXT && density.linkCount <= PLACEHOLDER_MAX_LINKS;
  const placeholderPhrase = (strong: string[], weak: string[]): string | null =>
    contains(visible, strong) ?? (thinEnoughForPlaceholder ? contains(visible, weak) : null);

  // --- Bot protection: measurement blocked, business status unknown ---------------
  if (botHeader || challengePhrase || weakMarker) {
    return {
      status: 'bot_protection',
      reason:
        'A bot-protection challenge was served instead of the site. The website may well be healthy — we simply could not read it.',
      evidence: [
        ...evidence,
        botHeader
          ? `protection header: ${botHeader}`
          : challengePhrase
            ? `challenge text: "${challengePhrase}"`
            : `"${weakMarker}" on a page with ${density.textLength} characters and ${density.linkCount} link(s)`,
      ],
      confidence: botHeader || challengePhrase ? 'high' : 'medium',
    };
  }

  const code = probe.httpStatus;

  if (code === 401 || code === 403 || code === 429 || code === 451) {
    return {
      status: 'access_blocked',
      reason: `The server refused our request with HTTP ${code}. This is an access restriction, not proof the site is offline.`,
      evidence,
      confidence: 'medium',
    };
  }

  if (code != null && code >= 500) {
    const construction = placeholderPhrase(CONSTRUCTION_STRONG, CONSTRUCTION_WEAK);
    if (construction) {
      return {
        status: 'under_construction',
        reason: 'The server returned an error page announcing maintenance or an upcoming launch.',
        evidence: [...evidence, `page text: "${construction}"`],
        confidence: 'medium',
      };
    }
    return {
      status: 'unknown_needs_review',
      reason: `The server returned HTTP ${code}. A single failed request is not enough to conclude the site is dead.`,
      evidence,
      confidence: 'low',
    };
  }

  if (code != null && code >= 400) {
    return {
      status: 'partially_broken',
      reason: `The homepage itself returned HTTP ${code}, so visitors landing on the root URL see an error.`,
      evidence,
      confidence: 'medium',
    };
  }

  if (code == null) {
    return {
      status: 'unknown_needs_review',
      reason: 'No HTTP response was recorded for this domain.',
      evidence: evidence.length ? evidence : ['no response captured'],
      confidence: 'low',
    };
  }

  // --- 2xx/3xx with a body: read the content ------------------------------------
  const forSale = placeholderPhrase(FOR_SALE_STRONG, FOR_SALE_WEAK);
  if (forSale) {
    return {
      status: 'domain_for_sale',
      reason: 'The domain resolves to a sales landing page rather than a business website.',
      evidence: [...evidence, `page text: "${forSale}"`],
      confidence: 'high',
    };
  }

  const parked = placeholderPhrase(PARKED_STRONG, PARKED_WEAK);
  if (parked) {
    return {
      status: 'parked_domain',
      reason: 'The domain serves a registrar parking or default server page, not a real website.',
      evidence: [...evidence, `page text: "${parked}"`],
      confidence: 'high',
    };
  }

  const construction = placeholderPhrase(CONSTRUCTION_STRONG, CONSTRUCTION_WEAK);
  if (construction) {
    return {
      status: 'under_construction',
      reason: 'The site advertises itself as under construction or launching soon.',
      evidence: [...evidence, `page text: "${construction}"`],
      confidence: 'high',
    };
  }

  const { textLength, linkCount, hasNav } = density;
  evidence.push(`content: ${textLength} chars of text, ${linkCount} links, nav=${hasNav}`);

  if (textLength < 200 && linkCount < 3) {
    return {
      status: 'under_construction',
      reason:
        'The homepage rendered almost no content and almost no navigation, which is consistent with a placeholder rather than a working site.',
      evidence,
      confidence: 'low',
    };
  }

  if (crossedHost(probe.redirectChain, probe.finalUrl)) {
    return {
      status: 'live_after_redirect',
      reason: 'The submitted domain redirects to a different host that serves the live website.',
      evidence,
      confidence: 'high',
    };
  }

  return {
    status: 'live',
    reason: 'The homepage responded successfully and served real page content.',
    evidence,
    confidence: 'high',
  };
}

/** True when we hold enough of the site to audit it honestly. */
export function isAuditable(status: WebsiteStatus): boolean {
  return status === 'live' || status === 'live_after_redirect' || status === 'partially_broken';
}

/** True when the company demonstrably has no usable web presence at all. */
export function isMissingWebsite(status: WebsiteStatus): boolean {
  return (
    status === 'no_website' ||
    status === 'invalid_domain' ||
    status === 'dns_failure' ||
    status === 'parked_domain' ||
    status === 'domain_for_sale'
  );
}

/** True when we were prevented from measuring and must not guess. */
export function isMeasurementBlocked(status: WebsiteStatus): boolean {
  return (
    status === 'bot_protection' ||
    status === 'access_blocked' ||
    status === 'timeout' ||
    status === 'unknown_needs_review'
  );
}

export const WEBSITE_STATUS_LABELS: Record<WebsiteStatus, string> = {
  live: 'Live',
  live_after_redirect: 'Live after redirect',
  dns_failure: 'DNS failure',
  ssl_failure: 'SSL/TLS failure',
  timeout: 'Timeout',
  access_blocked: 'Access blocked',
  bot_protection: 'Bot protection detected',
  parked_domain: 'Parked domain',
  domain_for_sale: 'Domain for sale',
  under_construction: 'Under construction',
  partially_broken: 'Partially broken',
  invalid_domain: 'Invalid domain',
  no_website: 'No website',
  unknown_needs_review: 'Unknown — needs review',
};
